# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 447b38f34abc4b42b064ae5dee9c2c4719bc53f3d8654f3a2684002a0bb7a3cc37b9fdb6e2ba0b5fcdadd2d162833291e218737c8bf9503cea10b05315ec60a5

test:
  secret_key_base: b90ba436bad94c41399fba5f8092db9fecf748d6e72395764a41f8a1de371886f40623c8696b59f7360123e2331eb0fdfcfad57f79584829b71e6ef7d5c017d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
